version: '3.8'

services:
  aes-telegram-bot:
    build: .
    env_file: .env
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - qdrant  # Добавляем зависимость от Qdrant
    networks:
      - bot-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bot-network

  qdrant:
    image: qdrant/qdrant:v1.8.0  # Рекомендуется использовать конкретную версию
    restart: unless-stopped
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - bot-network

volumes:
  redis_data:
  qdrant_data:

networks:
  bot-network:
    driver: bridge